l_italian:
 EU5DISPLAYNAME: "da Europa Universalis V a Victoria 3"
 EU5GAME: "Europa Universalis V"
 VIC3GAME: "Victoria 3"
 EU5FOLDER: "Cartella di installazione di Europa Universalis V"
 EU5FOLDERTIP: "Il percorso in cui è installato Europa Universalis V"
 EU5DOC: "Cartella dei documenti di Europa Universalis V"
 EU5DOCTIP: "Un percorso in cui Europa Universalis V conserva file temporanei"
 VIC3FOLDER: "Cartella di installazione di Victoria 3"
 VIC3FOLDERTIP: "Il percorso in cui è installato Victoria 3"
 VIC3MOD: "Cartella delle mod per Victoria 3"
 VIC3MODTIP: "Il percorso in cui Victoria 3 memorizza le mod"
 EU5FILE: "Percorso dell'eseguibile del convertitore"
 EU5FILETIP: "Percorso di EU5ToVic3Converter.exe"
 EU5SAVE: "Percorso per il savegame EU5"
 EU5SAVETIP: "Percorso per il tuo savegame da EU5"
