l_german:
 EU5DISPLAYNAME: "von Europa Universalis V zu Victoria 3"
 EU5GAME: "Europa Universalis V"
 VIC3GAME: "Victoria 3"
 EU5FOLDER: "Europa Universalis V-Installationsverzeichnis"
 EU5FOLDERTIP: "Der Pfad auf Ihrem Computer, auf dem Europa Universalis V installiert ist"
 EU5DOC: "Europa Universalis V-Dokumentenverzeichnis"
 EU5DOCTIP: "Ein Pfad auf Ihrem Computer, in dem Europa Universalis V temporäre Dateien speichert"
 VIC3FOLDER: "Victoria 3-Installationsverzeichnis"
 VIC3FOLDERTIP: "Der Pfad auf Ihrem Computer, auf dem Victoria 3 installiert ist"
 VIC3MOD: "Victoria 3 Mod-Verzeichnis"
 VIC3MODTIP: "Der Pfad auf Ihrem Computer, auf dem Victoria 3 Mods speichert"
 EU5FILE: "Pfad zur ausführbaren Datei des Konverters"
 EU5FILETIP: "Pfad zu EU5ToVic3Converter.exe"
 EU5SAVE: "Pfad zum EU5-Savegame"
 EU5SAVETIP: "Pfad zu Ihrem Savegame von EU5"
