l_french:
 EU5DISPLAYNAME: "d'Europa Universalis V à Victoria 3"
 EU5GAME: "Europa Universalis V"
 VIC3GAME: "Victoria 3"
 EU5FOLDER: "Répertoire d'installation d'Europa Universalis V"
 EU5FOLDERTIP: "Le chemin sur votre ordinateur où Europa Universalis V est installé"
 EU5DOC: "Répertoire des documents Europa Universalis V"
 EU5DOCTIP: "Un chemin sur votre ordinateur où Europa Universalis V conserve des fichiers temporaires"
 VIC3FOLDER: "Répertoire d'installation de Victoria 3"
 VIC3FOLDERTIP: "Le chemin sur votre ordinateur où Victoria 3 est installé"
 VIC3MOD: "Répertoire des mods Victoria 3"
 VIC3MODTIP: "Le chemin sur votre ordinateur où Victoria 3 stocke les mods"
 EU5FILE: "Chemin vers l'exécutable du convertisseur"
 EU5FILETIP: "Chemin vers EU5ToVic3Converter.exe"
 EU5SAVE: "Chemin vers la sauvegarde de EU5"
 EU5SAVETIP: "Chemin vers votre sauvegarde depuis EU5"
