l_russian:
 EU5DISPLAYNAME: "из Европы Универсалис V в Викторию 3"
 EU5GAME: "Европа Универсалис V"
 VIC3GAME: "Виктория 3"
 EU5FOLDER: "Европа Универсалис V Установить каталог"
 EU5FOLDERTIP: "Путь на вашем компьютере, где установлена Европа Универсалис V"
 EU5DOC: "Справочник документов Европа Универсалис V"
 EU5DOCTIP: "Путь на вашем компьютере, где Европа Универсалис V хранит временные файлы"
 VIC3FOLDER: "Установочный каталог Виктория 3"
 VIC3FOLDERTIP: "Путь на вашем компьютере, где установлена Виктория 3"
 VIC3MOD: "Виктория 3 Мод Каталог"
 VIC3MODTIP: "Путь на вашем компьютере, где хранятся моды Виктория 3"
 EU5FILE: "Путь к исполняемому файлу конвертера"
 EU5FILETIP: "Путь к EU5ToVic3Converter.exe"
 EU5SAVE: "Путь к сохранению игры EU5"
 EU5SAVETIP: "Путь к вашей сохраненной игре из EU5"
