l_english:
 EU5DISPLAYNAME: "Europa Universalis V to Victoria 3"
 EU5GAME: "Europa Universalis V"
 VIC3GAME: "Victoria 3"
 EU5FOLDER: "Europa Universalis V Install Directory"
 EU5FOLDERTIP: "The path on your computer where Europa Universalis V is installed"
 EU5DOC: "Europa Universalis V Documents Directory"
 EU5DOCTIP: "A path on your computer where Europa Universalis V keeps temporary files"
 VIC3FOLDER: "Victoria 3 Install Directory"
 VIC3FOLDERTIP: "The path on your computer where Victoria 3 is installed"
 VIC3MOD: "Victoria 3 Mod Directory"
 VIC3MODTIP: "The path on your computer where Victoria 3 stores mods"
 EU5FILE: "Path to the converter executable"
 EU5FILETIP: "Path to EU5ToVic3Converter.exe"
 EU5SAVE: "Path to the EU5 savegame"
 EU5SAVETIP: "Path to your savegame from EU5"
