l_latin:
 EU5DISPLAYNAME: "ex Europa Universali ad Victoriam 3"
 EU5GAME: "Europa Universalis V"
 VIC3GAME: "Victoria 3"
 EU5FOLDER: "Scapus locationis Europae Universalis IV"
 EU5FOLDERTIP: "Via in qua locatus est ludus Europa Universalis V"
 EU5DOC: "Scapus documentorum Europae Universalis IV"
 EU5DOCTIP: "Via in qua Europa Universalis V scribit fasciculos temporales"
 VIC3FOLDER: "Scapus locationis Victoriae 3"
 VIC3FOLDERTIP: "Via in qua locatus est ludus Victoria 3"
 VIC3MOD: "Scapus correctionum Victoriae 3"
 VIC3MODTIP: "Via in qua locatae sunt correctiones Victoriae 3"
 EU5FILE: "Via programmatis"
 EU5FILETIP: "Via ad EU5ToVic3Converter.exe"
 EU5SAVE: "Via ad conditum EU5"
 EU5SAVETIP: "Via ad conditum EU5"
